use Ejercicio1

insert into Proveedor values(	1	,	'Proveedor 01'	,	'Domicilio 1001'	,	'La Plata'	)
insert into Proveedor values(	2	,	'Proveedor 02'	,	'Domicilio 1002'	,	'Merlo'	)
insert into Proveedor values(	3	,	'Proveedor 03'	,	'Domicilio 1003'	,	'Moron'	)
insert into Proveedor values(	4	,	'Proveedor 24'	,	'Domicilio 1002'	,	'Moreno'	)
insert into Proveedor values(	5	,	'Proveedor 25'	,	'Domicilio 1003'	,	'Liniers'	)
insert into Proveedor values(	6	,	'Proveedor 04'	,	'Domicilio 1001'	,	'La Plata'	)
insert into Proveedor values(	7	,	'Proveedor 05'	,	'Domicilio 1002'	,	'Merlo'	)
insert into Proveedor values(	8	,	'Proveedor 06'	,	'Domicilio 1003'	,	'Moron'	)
insert into Proveedor values(	9	,	'Proveedor 07'	,	'Domicilio 1002'	,	'Moreno'	)
insert into Proveedor values(	10	,	'Proveedor 08'	,	'Domicilio 1003'	,	'Liniers'	)
insert into Proveedor values(	11	,	'Proveedor 09'	,	'Domicilio 1001'	,	'La Plata'	)
insert into Proveedor values(	12	,	'Proveedor 10'	,	'Domicilio 1002'	,	'Merlo'	)
insert into Proveedor values(	13	,	'Proveedor 11'	,	'Domicilio 1003'	,	'Moron'	)
insert into Proveedor values(	14	,	'Proveedor 12'	,	'Domicilio 1002'	,	'Moreno'	)
insert into Proveedor values(	15	,	'Proveedor 13'	,	'Domicilio 1003'	,	'Liniers'	)
insert into Proveedor values(	16	,	'Proveedor 14'	,	'Domicilio 1001'	,	'La Plata'	)
insert into Proveedor values(	17	,	'Proveedor 15'	,	'Domicilio 1002'	,	'Merlo'	)
insert into Proveedor values(	18	,	'Proveedor 16'	,	'Domicilio 1003'	,	'Moron'	)
insert into Proveedor values(	19	,	'Proveedor 17'	,	'Domicilio 1002'	,	'Moreno'	)
insert into Proveedor values(	20	,	'Proveedor 18'	,	'Domicilio 1003'	,	'Liniers'	)
insert into Proveedor values(	21	,	'Proveedor 19'	,	'Domicilio 1001'	,	'La Plata'	)
insert into Proveedor values(	22	,	'Proveedor 20'	,	'Domicilio 1002'	,	'Merlo'	)
insert into Proveedor values(	23	,	'Proveedor 21'	,	'Domicilio 1003'	,	'Moron'	)
insert into Proveedor values(	24	,	'Proveedor 22'	,	'Domicilio 1002'	,	'Moreno'	)
insert into Proveedor values(	25	,	'Proveedor 23'	,	'Domicilio 1003'	,	'Liniers'	)
insert into Proveedor values(	26	,	'Proveedor 26'	,	'Domicilio 1321'	,	'Merlo'	)



insert into Articulo values(	1	,	'Articulo 01'	,	37.65	)
insert into Articulo values(	2	,	'Articulo 02'	,	50.86	)
insert into Articulo values(	3	,	'Articulo 03'	,	0.97	)
insert into Articulo values(	4	,	'Articulo 04'	,	13.43	)
insert into Articulo values(	5	,	'Articulo 01'	,	1.46	)
insert into Articulo values(	6	,	'Articulo 02'	,	30.05	)
insert into Articulo values(	7	,	'Articulo 03'	,	21.65	)
insert into Articulo values(	8	,	'Articulo 04'	,	28.36	)
insert into Articulo values(	9	,	'Articulo 01'	,	19.09	)
insert into Articulo values(	10	,	'Articulo 02'	,	8.92	)
insert into Articulo values(	11	,	'Articulo 03'	,	20.53	)
insert into Articulo values(	12	,	'Articulo 04'	,	40.38	)
insert into Articulo values(	13	,	'Articulo 01'	,	27.81	)
insert into Articulo values(	14	,	'Articulo 01'	,	29.37	)
insert into Articulo values(	15	,	'Articulo 02'	,	1.15	)
insert into Articulo values(	16	,	'Articulo 03'	,	35.59	)
insert into Articulo values(	17	,	'Articulo 04'	,	21.05	)
insert into Articulo values(	18	,	'Articulo 01'	,	12.01	)
insert into Articulo values(	19	,	'Articulo 02'	,	15.23	)
insert into Articulo values(	20	,	'Articulo 03'	,	40.19	)
insert into Articulo values(	21	,	'Articulo 04'	,	48.7	)
insert into Articulo values(	22	,	'Articulo 01'	,	19.89	)
insert into Articulo values(	23	,	'Articulo 02'	,	1.05	)
insert into Articulo values(	24	,	'Articulo 03'	,	34.54	)
insert into Articulo values(	25	,	'Articulo 04'	,	7.28	)
insert into Articulo values(	26	,	'Articulo 01'	,	21.22	)
insert into Articulo values(	27	,	'Articulo 01'	,	43.67	)
insert into Articulo values(	28	,	'Articulo 02'	,	1.67	)
insert into Articulo values(	29	,	'Articulo 03'	,	5.56	)
insert into Articulo values(	30	,	'Articulo 04'	,	0.05	)
insert into Articulo values(	31	,	'Articulo 05'	,	15	)
insert into Articulo values(	32	,	'Articulo 06'	,	20	)
insert into Articulo values(	33	,	'Articulo 06'	,	25	)
insert into Articulo values(	34	,	'Articulo 07'	,	8	)
insert into Articulo values(	35	,	'Articulo 35'	,	50.86	)
insert into Articulo values(	36	,	'Articulo 36'	,	0.05	)
insert into Articulo values(	37	,	'Articulo 37'	,	60.00	)


insert into Almacen values(	1	,	'Responsable 01'	)
insert into Almacen values(	2	,	'Responsable 02'	)
insert into Almacen values(	3	,	'Responsable 03'	)
insert into Almacen values(	4	,	'Responsable 04'	)
insert into Almacen values(	5	,	'Responsable 05'	)
insert into Almacen values(	6	,	'Responsable 06'	)
insert into Almacen values(	7	,	'Responsable 07'	)


insert into material values(	1	,	'Material 01'	)
insert into material values(	2	,	'Material 02'	)
insert into material values(	3	,	'Material 03'	)
insert into material values(	4	,	'Material 04'	)
insert into material values(	5	,	'Material 05'	)
insert into material values(	6	,	'Material 06'	)
insert into material values(	7	,	'Material 07'	)
insert into material values(	8	,	'Material 08'	)
insert into material values(	9	,	'Material 09'	)
insert into material values(	10	,	'Material 10'	)
insert into material values(	11	,	'Material 11'	)
insert into material values(	12	,	'Material 12'	)
insert into material values(	13	,	'Material 13'	)
insert into material values(	14	,	'Material 14'	)
insert into material values(	15	,	'Material 15'	)
insert into material values(	16	,	'Material 16'	)
insert into material values(	17	,	'Material 17'	)

insert into provisto_por values(	16	,	7	)
insert into provisto_por values(	5	,	9	)
insert into provisto_por values(	10	,	16	)
insert into provisto_por values(	1	,	12	)
insert into provisto_por values(	9	,	24	)
insert into provisto_por values(	1	,	5	)
insert into provisto_por values(	10	,	14	)
insert into provisto_por values(	5	,	20	)
insert into provisto_por values(	6	,	16	)
insert into provisto_por values(	2	,	25	)
insert into provisto_por values(	15	,	13	)
insert into provisto_por values(	12	,	21	)
insert into provisto_por values(	1	,	24	)
insert into provisto_por values(	15	,	21	)
insert into provisto_por values(	4	,	24	)
insert into provisto_por values(	14	,	9	)
insert into provisto_por values(	11	,	11	)
insert into provisto_por values(	8	,	5	)
insert into provisto_por values(	1	,	10	)
insert into provisto_por values(	2	,	19	)
insert into provisto_por values(	5	,	5	)
insert into provisto_por values(	7	,	21	)
insert into provisto_por values(	1	,	18	)
insert into provisto_por values(	7	,	18	)
insert into provisto_por values(	9	,	20	)
insert into provisto_por values(	12	,	5	)
insert into provisto_por values(	14	,	6	)
insert into provisto_por values(	14	,	25	)
insert into provisto_por values(	5	,	15	)
insert into provisto_por values(	3	,	7	)
insert into provisto_por values(	7	,	18	)
insert into provisto_por values(	15	,	21	)
insert into provisto_por values(	9	,	20	)
insert into provisto_por values(	3	,	1	)
insert into provisto_por values(	3	,	18	)
insert into provisto_por values(	11	,	24	)
insert into provisto_por values(	11	,	13	)
insert into provisto_por values(	5	,	14	)
insert into provisto_por values(	14	,	22	)
insert into provisto_por values(	9	,	10	)
insert into provisto_por values(	14	,	5	)
insert into provisto_por values(	8	,	16	)
insert into provisto_por values(	7	,	23	)
insert into provisto_por values(	8	,	4	)
insert into provisto_por values(	10	,	9	)
insert into provisto_por values(	11	,	11	)
insert into provisto_por values(	6	,	13	)
insert into provisto_por values(	5	,	12	)
insert into provisto_por values(	6	,	14	)
insert into provisto_por values(	14	,	15	)
insert into provisto_por values(	13	,	8	)
insert into provisto_por values(	14	,	10	)
insert into provisto_por values(	8	,	16	)
insert into provisto_por values(	6	,	18	)
insert into provisto_por values(	8	,	8	)
insert into provisto_por values(	12	,	13	)
insert into provisto_por values(	3	,	3	)
insert into provisto_por values(	10	,	14	)
insert into provisto_por values(	3	,	5	)
insert into provisto_por values(	7	,	24	)
insert into provisto_por values(	11	,	21	)
insert into provisto_por values(	7	,	10	)
insert into provisto_por values(	12	,	16	)
insert into provisto_por values(	1	,	9	)
insert into provisto_por values(	3	,	3	)
insert into provisto_por values(	13	,	16	)
insert into provisto_por values(	14	,	4	)
insert into provisto_por values(	9	,	14	)
insert into provisto_por values(	6	,	15	)
insert into provisto_por values(	11	,	19	)
insert into provisto_por values(	8	,	14	)
insert into provisto_por values(	5	,	22	)
insert into provisto_por values(	13	,	24	)
insert into provisto_por values(	9	,	17	)
insert into provisto_por values(	13	,	18	)
insert into provisto_por values(	6	,	6	)
insert into provisto_por values(	7	,	19	)
insert into provisto_por values(	5	,	2	)
insert into provisto_por values(	10	,	11	)
insert into provisto_por values(	13	,	15	)
insert into provisto_por values(	10	,	16	)
insert into provisto_por values(	6	,	16	)
insert into provisto_por values(	3	,	20	)
insert into provisto_por values(	11	,	5	)
insert into provisto_por values(	6	,	24	)
insert into provisto_por values(	4	,	13	)
insert into provisto_por values(	14	,	4	)
insert into provisto_por values(	3	,	12	)
insert into provisto_por values(	8	,	14	)
insert into provisto_por values(	15	,	14	)
insert into provisto_por values(	12	,	3	)
insert into provisto_por values(	12	,	7	)
insert into provisto_por values(	13	,	10	)
insert into provisto_por values(	7	,	24	)
insert into provisto_por values(	14	,	2	)
insert into provisto_por values(	9	,	1	)
insert into provisto_por values(	9	,	18	)
insert into provisto_por values(	13	,	19	)
insert into provisto_por values(	11	,	14	)
insert into provisto_por values(	12	,	14	)
insert into provisto_por values(	6	,	19	)
insert into provisto_por values(	15	,	15	)
insert into provisto_por values(	5	,	25	)
insert into provisto_por values(	1	,	3	)
insert into provisto_por values(	1	,	9	)
insert into provisto_por values(	12	,	11	)
insert into provisto_por values(	14	,	25	)
insert into provisto_por values(	3	,	10	)
insert into provisto_por values(	14	,	13	)
insert into provisto_por values(	3	,	7	)
insert into provisto_por values(	13	,	17	)
insert into provisto_por values(	14	,	1	)
insert into provisto_por values(	11	,	23	)
insert into provisto_por values(	2	,	17	)
insert into provisto_por values(	12	,	2	)
insert into provisto_por values(	15	,	8	)
insert into provisto_por values(	7	,	23	)
insert into provisto_por values(	13	,	11	)
insert into provisto_por values(	1	,	9	)
insert into provisto_por values(	10	,	3	)
insert into provisto_por values(	15	,	20	)
insert into provisto_por values(	11	,	4	)
insert into provisto_por values(	14	,	6	)
insert into provisto_por values(	7	,	7	)
insert into provisto_por values(	9	,	12	)
insert into provisto_por values(	10	,	21	)
insert into provisto_por values(	13	,	14	)
insert into provisto_por values(	2	,	19	)
insert into provisto_por values(	2	,	15	)
insert into provisto_por values(	8	,	14	)
insert into provisto_por values(	5	,	21	)
insert into provisto_por values(	6	,	19	)
insert into provisto_por values(	4	,	22	)
insert into provisto_por values(	10	,	3	)
insert into provisto_por values(	2	,	21	)
insert into provisto_por values(	8	,	8	)
insert into provisto_por values(	12	,	15	)
insert into provisto_por values(	11	,	5	)
insert into provisto_por values(	4	,	17	)
insert into provisto_por values(	13	,	17	)
insert into provisto_por values(	4	,	6	)
insert into provisto_por values(	14	,	9	)
insert into provisto_por values(	12	,	7	)
insert into provisto_por values(	7	,	5	)
insert into provisto_por values(	2	,	19	)
insert into provisto_por values(	9	,	25	)
insert into provisto_por values(	4	,	10	)
insert into provisto_por values(	5	,	24	)
insert into provisto_por values(	5	,	21	)
insert into provisto_por values(	12	,	13	)
insert into provisto_por values(	12	,	10	)
insert into provisto_por values(	1	,	26	)
insert into provisto_por values(	2	,	26	)
insert into provisto_por values(	3	,	26	)
insert into provisto_por values(	4	,	26	)
insert into provisto_por values(	5	,	26	)
insert into provisto_por values(	6	,	26	)
insert into provisto_por values(	7	,	26	)
insert into provisto_por values(	8	,	26	)
insert into provisto_por values(	9	,	26	)
insert into provisto_por values(	10	,	26	)
insert into provisto_por values(	11	,	26	)
insert into provisto_por values(	12	,	26	)
insert into provisto_por values(	13	,	26	)
insert into provisto_por values(	14	,	26	)
insert into provisto_por values(	15	,	26	)
insert into provisto_por values(	16	,	26	)
insert into provisto_por values(	17	,	26	)



insert into tiene  values(	1	,	34	)
insert into tiene  values(	1	,	2	)
insert into tiene  values(	5	,	6	)
insert into tiene  values(	1	,	34	)
insert into tiene  values(	6	,	22	)
insert into tiene  values(	6	,	2	)
insert into tiene  values(	1	,	29	)
insert into tiene  values(	2	,	29	)
insert into tiene  values(	1	,	2	)
insert into tiene  values(	7	,	11	)
insert into tiene  values(	1	,	4	)
insert into tiene  values(	3	,	3	)
insert into tiene  values(	3	,	34	)
insert into tiene  values(	1	,	1	)
insert into tiene  values(	3	,	23	)
insert into tiene  values(	1	,	29	)
insert into tiene  values(	7	,	31	)
insert into tiene  values(	1	,	24	)
insert into tiene  values(	7	,	33	)
insert into tiene  values(	2	,	12	)
insert into tiene  values(	3	,	29	)
insert into tiene  values(	3	,	3	)
insert into tiene  values(	3	,	5	)
insert into tiene  values(	5	,	31	)
insert into tiene  values(	2	,	1	)
insert into tiene  values(	3	,	22	)
insert into tiene  values(	5	,	5	)
insert into tiene  values(	2	,	23	)
insert into tiene  values(	3	,	11	)
insert into tiene  values(	4	,	10	)
insert into tiene  values(	7	,	12	)
insert into tiene  values(	7	,	30	)
insert into tiene  values(	7	,	33	)
insert into tiene  values(	4	,	8	)
insert into tiene  values(	3	,	11	)
insert into tiene  values(	2	,	16	)
insert into tiene  values(	6	,	15	)
insert into tiene  values(	1	,	26	)
insert into tiene  values(	2	,	24	)
insert into tiene  values(	3	,	7	)
insert into tiene  values(	3	,	2	)
insert into tiene  values(	4	,	28	)
insert into tiene  values(	4	,	2	)
insert into tiene  values(	7	,	27	)
insert into tiene  values(	6	,	8	)
insert into tiene  values(	7	,	24	)
insert into tiene  values(	5	,	33	)
insert into tiene  values(	5	,	8	)
insert into tiene  values(	7	,	10	)
insert into tiene  values(	5	,	27	)
insert into tiene  values(	2	,	20	)
insert into tiene  values(	3	,	32	)
insert into tiene  values(	5	,	2	)
insert into tiene  values(	3	,	31	)
insert into tiene  values(	3	,	9	)
insert into tiene  values(	5	,	27	)
insert into tiene  values(	5	,	27	)
insert into tiene  values(	4	,	20	)
insert into tiene  values(	6	,	21	)
insert into tiene  values(	3	,	18	)
insert into tiene  values(	2	,	16	)
insert into tiene  values(	1	,	34	)
insert into tiene  values(	7	,	28	)
insert into tiene  values(	1	,	2	)
insert into tiene  values(	1	,	25	)
insert into tiene  values(	3	,	22	)
insert into tiene  values(	1	,	23	)
insert into tiene  values(	7	,	16	)
insert into tiene  values(	3	,	16	)
insert into tiene  values(	4	,	33	)
insert into tiene  values(	6	,	19	)
insert into tiene  values(	3	,	12	)
insert into tiene  values(	1	,	23	)
insert into tiene  values(	3	,	33	)
insert into tiene  values(	2	,	18	)
insert into tiene  values(	6	,	14	)
insert into tiene  values(	2	,	23	)
insert into tiene  values(	3	,	12	)
insert into tiene  values(	7	,	20	)
insert into tiene  values(	1	,	28	)
insert into tiene  values(	3	,	1	)
insert into tiene  values(	3	,	9	)
insert into tiene  values(	6	,	14	)
insert into tiene  values(	2	,	28	)
insert into tiene  values(	5	,	13	)
insert into tiene  values(	7	,	32	)
insert into tiene  values(	1	,	17	)
insert into tiene  values(	2	,	22	)
insert into tiene  values(	7	,	31	)
insert into tiene  values(	6	,	2	)
insert into tiene  values(	7	,	11	)
insert into tiene  values(	7	,	29	)
insert into tiene  values(	2	,	31	)
insert into tiene  values(	5	,	14	)
insert into tiene  values(	3	,	29	)
insert into tiene  values(	6	,	18	)
insert into tiene  values(	5	,	23	)
insert into tiene  values(	3	,	18	)
insert into tiene  values(	2	,	3	)
insert into tiene  values(	6	,	25	)
insert into tiene  values(	7	,	22	)
insert into tiene  values(	4	,	25	)
insert into tiene  values(	7	,	9	)
insert into tiene  values(	5	,	27	)
insert into tiene  values(	5	,	1	)
insert into tiene  values(	6	,	23	)
insert into tiene  values(	7	,	28	)
insert into tiene  values(	6	,	27	)
insert into tiene  values(	3	,	15	)
insert into tiene  values(	4	,	21	)
insert into tiene  values(	4	,	7	)
insert into tiene  values(	2	,	23	)
insert into tiene  values(	5	,	32	)
insert into tiene  values(	4	,	7	)
insert into tiene  values(	2	,	15	)
insert into tiene  values(	3	,	21	)
insert into tiene  values(	1	,	32	)
insert into tiene  values(	5	,	14	)
insert into tiene  values(	1	,	26	)
insert into tiene  values(	5	,	29	)
insert into tiene  values(	1	,	7	)
insert into tiene  values(	1	,	19	)
insert into tiene  values(	1	,	32	)
insert into tiene  values(	6	,	19	)
insert into tiene  values(	6	,	32	)


insert into compuesto_por values(	12	,	10	)
insert into compuesto_por values(	24	,	11	)
insert into compuesto_por values(	11	,	15	)
insert into compuesto_por values(	7	,	2	)
insert into compuesto_por values(	4	,	11	)
insert into compuesto_por values(	7	,	9	)
insert into compuesto_por values(	28	,	6	)
insert into compuesto_por values(	10	,	6	)
insert into compuesto_por values(	31	,	7	)
insert into compuesto_por values(	27	,	10	)
insert into compuesto_por values(	11	,	14	)
insert into compuesto_por values(	28	,	12	)
insert into compuesto_por values(	1	,	9	)
insert into compuesto_por values(	28	,	6	)
insert into compuesto_por values(	5	,	6	)
insert into compuesto_por values(	34	,	11	)
insert into compuesto_por values(	7	,	5	)
insert into compuesto_por values(	4	,	15	)
insert into compuesto_por values(	13	,	15	)
insert into compuesto_por values(	1	,	15	)
insert into compuesto_por values(	34	,	13	)
insert into compuesto_por values(	19	,	14	)
insert into compuesto_por values(	28	,	10	)
insert into compuesto_por values(	29	,	12	)
insert into compuesto_por values(	26	,	3	)
insert into compuesto_por values(	13	,	10	)
insert into compuesto_por values(	30	,	7	)
insert into compuesto_por values(	33	,	8	)
insert into compuesto_por values(	28	,	4	)
insert into compuesto_por values(	32	,	2	)
insert into compuesto_por values(	3	,	11	)
insert into compuesto_por values(	2	,	14	)
insert into compuesto_por values(	25	,	3	)
insert into compuesto_por values(	12	,	13	)
insert into compuesto_por values(	15	,	5	)
insert into compuesto_por values(	7	,	2	)
insert into compuesto_por values(	15	,	3	)
insert into compuesto_por values(	22	,	12	)
insert into compuesto_por values(	32	,	2	)
insert into compuesto_por values(	7	,	12	)
insert into compuesto_por values(	25	,	3	)
insert into compuesto_por values(	19	,	2	)
insert into compuesto_por values(	13	,	9	)
insert into compuesto_por values(	29	,	4	)
insert into compuesto_por values(	9	,	1	)
insert into compuesto_por values(	7	,	1	)
insert into compuesto_por values(	17	,	3	)
insert into compuesto_por values(	23	,	3	)
insert into compuesto_por values(	19	,	9	)
insert into compuesto_por values(	31	,	6	)
insert into compuesto_por values(	6	,	11	)
insert into compuesto_por values(	6	,	6	)
insert into compuesto_por values(	20	,	1	)
insert into compuesto_por values(	23	,	9	)
insert into compuesto_por values(	15	,	9	)
insert into compuesto_por values(	8	,	4	)
insert into compuesto_por values(	14	,	7	)
insert into compuesto_por values(	19	,	12	)
insert into compuesto_por values(	24	,	6	)
insert into compuesto_por values(	4	,	12	)
insert into compuesto_por values(	32	,	8	)
insert into compuesto_por values(	8	,	12	)
insert into compuesto_por values(	1	,	1	)
insert into compuesto_por values(	8	,	6	)
insert into compuesto_por values(	7	,	13	)
insert into compuesto_por values(	12	,	10	)
insert into compuesto_por values(	7	,	15	)
insert into compuesto_por values(	23	,	10	)
insert into compuesto_por values(	12	,	10	)
insert into compuesto_por values(	34	,	12	)
insert into compuesto_por values(	4	,	6	)
insert into compuesto_por values(	33	,	12	)
insert into compuesto_por values(	32	,	15	)
insert into compuesto_por values(	29	,	6	)
insert into compuesto_por values(	16	,	5	)
insert into compuesto_por values(	5	,	13	)
insert into compuesto_por values(	29	,	7	)
insert into compuesto_por values(	26	,	14	)
insert into compuesto_por values(	16	,	14	)
insert into compuesto_por values(	15	,	8	)
insert into compuesto_por values(	30	,	9	)
insert into compuesto_por values(	8	,	4	)
insert into compuesto_por values(	14	,	13	)
insert into compuesto_por values(	25	,	7	)
insert into compuesto_por values(	23	,	13	)
insert into compuesto_por values(	34	,	3	)
insert into compuesto_por values(	33	,	8	)
insert into compuesto_por values(	24	,	6	)
insert into compuesto_por values(	5	,	8	)
insert into compuesto_por values(	11	,	1	)
insert into compuesto_por values(	2	,	4	)
insert into compuesto_por values(	32	,	7	)
insert into compuesto_por values(	26	,	1	)
insert into compuesto_por values(	34	,	6	)
insert into compuesto_por values(	2	,	7	)
insert into compuesto_por values(	21	,	12	)
insert into compuesto_por values(	20	,	12	)
insert into compuesto_por values(	26	,	6	)
insert into compuesto_por values(	1	,	1	)
insert into compuesto_por values(	11	,	10	)
insert into compuesto_por values(	37	,	1	)
insert into compuesto_por values(	37	,	2	)
insert into compuesto_por values(	37	,	3	)
insert into compuesto_por values(	37	,	4	)
insert into compuesto_por values(	37	,	5	)
insert into compuesto_por values(	37	,	6	)
insert into compuesto_por values(	37	,	7	)
insert into compuesto_por values(	37	,	8	)
insert into compuesto_por values(	37	,	9	)
insert into compuesto_por values(	37	,	10	)
insert into compuesto_por values(	37	,	11	)
insert into compuesto_por values(	37	,	12	)
insert into compuesto_por values(	37	,	13	)
insert into compuesto_por values(	37	,	14	)
insert into compuesto_por values(	37	,	15	)
insert into compuesto_por values(	37	,	16	)

